channels:
- conda-forge
dependencies:
- python=3.10.9
- pip<=22.3.1
- pip:
  - mlflow==2.9.2
  - numpy==1.22.4
  - pandas==1.4.3
  - psutil==7.1.3
  - scikit-learn==1.3.2
  - scipy==1.13.1
  - xgboost==2.0.3
name: mlflow-env
